import { CircuitPreset } from "../types/circuit";

export const CIRCUIT_PRESETS: CircuitPreset[] = [
  {
    id: "voltage_divider",
    title: "1. Voltage Divider & Ohm's Law",
    category: "Basic Circuits",
    description: "12V DC source connected to two resistors (1kΩ and 2kΩ) with a Voltmeter measuring output.",
    components: [
      {
        id: "dc1",
        type: "dc_voltage",
        label: "V1 (12V)",
        x: 100,
        y: 200,
        rotation: 0,
        pins: [
          { id: "pos", relX: 0, relY: -30 },
          { id: "neg", relX: 0, relY: 30 },
        ],
        params: { voltage: 12 },
        state: {},
      },
      {
        id: "r1",
        type: "resistor",
        label: "R1 (1kΩ)",
        x: 250,
        y: 100,
        rotation: 90,
        pins: [
          { id: "p1", relX: -40, relY: 0 },
          { id: "p2", relX: 40, relY: 0 },
        ],
        params: { resistance: 1000 },
        state: {},
      },
      {
        id: "r2",
        type: "resistor",
        label: "R2 (2kΩ)",
        x: 400,
        y: 200,
        rotation: 0,
        pins: [
          { id: "p1", relX: 0, relY: -40 },
          { id: "p2", relX: 0, relY: 40 },
        ],
        params: { resistance: 2000 },
        state: {},
      },
      {
        id: "vm1",
        type: "voltmeter",
        label: "Voltmeter V_out",
        x: 550,
        y: 200,
        rotation: 0,
        pins: [
          { id: "p1", relX: 0, relY: -30 },
          { id: "p2", relX: 0, relY: 30 },
        ],
        params: {},
        state: {},
      },
      {
        id: "gnd1",
        type: "ground",
        label: "GND",
        x: 250,
        y: 350,
        rotation: 0,
        pins: [{ id: "p1", relX: 0, relY: -20 }],
        params: {},
        state: {},
      },
    ],
    wires: [
      { id: "w1", fromComponentId: "dc1", fromPinId: "pos", toComponentId: "r1", toPinId: "p1" },
      { id: "w2", fromComponentId: "r1", fromPinId: "p2", toComponentId: "r2", toPinId: "p1" },
      { id: "w3", fromComponentId: "r1", fromPinId: "p2", toComponentId: "vm1", toPinId: "p1" },
      { id: "w4", fromComponentId: "dc1", fromPinId: "neg", toComponentId: "gnd1", toPinId: "p1" },
      { id: "w5", fromComponentId: "r2", fromPinId: "p2", toComponentId: "gnd1", toPinId: "p1" },
      { id: "w6", fromComponentId: "vm1", fromPinId: "p2", toComponentId: "gnd1", toPinId: "p1" },
    ],
  },
  {
    id: "rc_filter",
    title: "2. RC Low-Pass Filter & Oscilloscope",
    category: "AC & Signal Processing",
    description: "AC Voltage Source (10V, 50Hz) passing through 1kΩ Resistor and 10µF Capacitor.",
    components: [
      {
        id: "ac1",
        type: "ac_voltage",
        label: "AC Signal (10V, 50Hz)",
        x: 100,
        y: 200,
        rotation: 0,
        pins: [
          { id: "pos", relX: 0, relY: -30 },
          { id: "neg", relX: 0, relY: 30 },
        ],
        params: { voltage: 10, frequency: 50, waveform: "sine" },
        state: {},
      },
      {
        id: "r1",
        type: "resistor",
        label: "R (1kΩ)",
        x: 250,
        y: 100,
        rotation: 90,
        pins: [
          { id: "p1", relX: -40, relY: 0 },
          { id: "p2", relX: 40, relY: 0 },
        ],
        params: { resistance: 1000 },
        state: {},
      },
      {
        id: "c1",
        type: "capacitor",
        label: "C (10µF)",
        x: 400,
        y: 200,
        rotation: 0,
        pins: [
          { id: "p1", relX: 0, relY: -30 },
          { id: "p2", relX: 0, relY: 30 },
        ],
        params: { capacitance: 0.00001 },
        state: {},
      },
      {
        id: "scope1",
        type: "scope_probe",
        label: "Oscilloscope Probe",
        x: 520,
        y: 150,
        rotation: 0,
        pins: [{ id: "p1", relX: 0, relY: 0 }],
        params: {},
        state: {},
      },
      {
        id: "gnd1",
        type: "ground",
        label: "GND",
        x: 250,
        y: 350,
        rotation: 0,
        pins: [{ id: "p1", relX: 0, relY: -20 }],
        params: {},
        state: {},
      },
    ],
    wires: [
      { id: "w1", fromComponentId: "ac1", fromPinId: "pos", toComponentId: "r1", toPinId: "p1" },
      { id: "w2", fromComponentId: "r1", fromPinId: "p2", toComponentId: "c1", toPinId: "p1" },
      { id: "w3", fromComponentId: "r1", fromPinId: "p2", toComponentId: "scope1", toPinId: "p1" },
      { id: "w4", fromComponentId: "ac1", fromPinId: "neg", toComponentId: "gnd1", toPinId: "p1" },
      { id: "w5", fromComponentId: "c1", fromPinId: "p2", toComponentId: "gnd1", toPinId: "p1" },
    ],
  },
  {
    id: "transistor_led",
    title: "3. Transistor Switch & LED Driver",
    category: "Semiconductors",
    description: "Toggle switch driving NPN transistor base to light up a glowing LED with 330Ω current limiting resistor.",
    components: [
      {
        id: "dc1",
        type: "dc_voltage",
        label: "Vcc (5V)",
        x: 100,
        y: 200,
        rotation: 0,
        pins: [
          { id: "pos", relX: 0, relY: -30 },
          { id: "neg", relX: 0, relY: 30 },
        ],
        params: { voltage: 5 },
        state: {},
      },
      {
        id: "sw1",
        type: "switch_spst",
        label: "Control Switch",
        x: 200,
        y: 100,
        rotation: 90,
        pins: [
          { id: "p1", relX: -30, relY: 0 },
          { id: "p2", relX: 30, relY: 0 },
        ],
        params: {},
        state: { isClosed: true },
      },
      {
        id: "r_base",
        type: "resistor",
        label: "R_base (10kΩ)",
        x: 320,
        y: 100,
        rotation: 90,
        pins: [
          { id: "p1", relX: -40, relY: 0 },
          { id: "p2", relX: 40, relY: 0 },
        ],
        params: { resistance: 10000 },
        state: {},
      },
      {
        id: "npn1",
        type: "npn_transistor",
        label: "2N2222 NPN",
        x: 420,
        y: 200,
        rotation: 0,
        pins: [
          { id: "base", relX: -30, relY: 0 },
          { id: "collector", relX: 20, relY: -30 },
          { id: "emitter", relX: 20, relY: 30 },
        ],
        params: { beta: 100 },
        state: {},
      },
      {
        id: "led1",
        type: "led",
        label: "Red LED",
        x: 440,
        y: 80,
        rotation: 180,
        pins: [
          { id: "anode", relX: 0, relY: -25 },
          { id: "cathode", relX: 0, relY: 25 },
        ],
        params: { ledColor: "#ef4444", forwardVoltage: 2.0 },
        state: {},
      },
      {
        id: "r_led",
        type: "resistor",
        label: "R_led (330Ω)",
        x: 300,
        y: 50,
        rotation: 90,
        pins: [
          { id: "p1", relX: -40, relY: 0 },
          { id: "p2", relX: 40, relY: 0 },
        ],
        params: { resistance: 330 },
        state: {},
      },
      {
        id: "gnd1",
        type: "ground",
        label: "GND",
        x: 300,
        y: 350,
        rotation: 0,
        pins: [{ id: "p1", relX: 0, relY: -20 }],
        params: {},
        state: {},
      },
    ],
    wires: [
      { id: "w1", fromComponentId: "dc1", fromPinId: "pos", toComponentId: "sw1", toPinId: "p1" },
      { id: "w2", fromComponentId: "dc1", fromPinId: "pos", toComponentId: "r_led", toPinId: "p1" },
      { id: "w3", fromComponentId: "sw1", fromPinId: "p2", toComponentId: "r_base", toPinId: "p1" },
      { id: "w4", fromComponentId: "r_base", fromPinId: "p2", toComponentId: "npn1", toPinId: "base" },
      { id: "w5", fromComponentId: "r_led", fromPinId: "p2", toComponentId: "led1", toPinId: "anode" },
      { id: "w6", fromComponentId: "led1", fromPinId: "cathode", toComponentId: "npn1", toPinId: "collector" },
      { id: "w7", fromComponentId: "npn1", fromPinId: "emitter", toComponentId: "gnd1", toPinId: "p1" },
      { id: "w8", fromComponentId: "dc1", fromPinId: "neg", toComponentId: "gnd1", toPinId: "p1" },
    ],
  },
  {
    id: "dc_motor_ctrl",
    title: "4. DC Motor Speed Control",
    category: "Electromechanical",
    description: "12V DC Motor driven by transistor with Flyback Diode protection and Fuse safety.",
    components: [
      {
        id: "dc1",
        type: "dc_voltage",
        label: "12V Battery",
        x: 100,
        y: 200,
        rotation: 0,
        pins: [
          { id: "pos", relX: 0, relY: -30 },
          { id: "neg", relX: 0, relY: 30 },
        ],
        params: { voltage: 12 },
        state: {},
      },
      {
        id: "fuse1",
        type: "fuse",
        label: "Fuse (2A)",
        x: 220,
        y: 100,
        rotation: 90,
        pins: [
          { id: "p1", relX: -30, relY: 0 },
          { id: "p2", relX: 30, relY: 0 },
        ],
        params: { currentLimit: 2.0 },
        state: {},
      },
      {
        id: "motor1",
        type: "dc_motor",
        label: "12V DC Motor",
        x: 380,
        y: 100,
        rotation: 0,
        pins: [
          { id: "p1", relX: -30, relY: 0 },
          { id: "p2", relX: 30, relY: 0 },
        ],
        params: { nominalVoltage: 12 },
        state: {},
      },
      {
        id: "gnd1",
        type: "ground",
        label: "GND",
        x: 250,
        y: 350,
        rotation: 0,
        pins: [{ id: "p1", relX: 0, relY: -20 }],
        params: {},
        state: {},
      },
    ],
    wires: [
      { id: "w1", fromComponentId: "dc1", fromPinId: "pos", toComponentId: "fuse1", toPinId: "p1" },
      { id: "w2", fromComponentId: "fuse1", fromPinId: "p2", toComponentId: "motor1", toPinId: "p1" },
      { id: "w3", fromComponentId: "motor1", fromPinId: "p2", toComponentId: "gnd1", toPinId: "p1" },
      { id: "w4", fromComponentId: "dc1", fromPinId: "neg", toComponentId: "gnd1", toPinId: "p1" },
    ],
  },
  {
    id: "logic_half_adder",
    title: "5. Digital Logic Gate Combination",
    category: "Digital Logic",
    description: "XOR and AND logic gates forming a Half Adder circuit with output LEDs.",
    components: [
      {
        id: "sw_a",
        type: "switch_spst",
        label: "Input A",
        x: 100,
        y: 100,
        rotation: 90,
        pins: [
          { id: "p1", relX: -30, relY: 0 },
          { id: "p2", relX: 30, relY: 0 },
        ],
        params: {},
        state: { isClosed: true },
      },
      {
        id: "sw_b",
        type: "switch_spst",
        label: "Input B",
        x: 100,
        y: 250,
        rotation: 90,
        pins: [
          { id: "p1", relX: -30, relY: 0 },
          { id: "p2", relX: 30, relY: 0 },
        ],
        params: {},
        state: { isClosed: false },
      },
      {
        id: "dc5v",
        type: "dc_voltage",
        label: "5V Logic Supply",
        x: 40,
        y: 180,
        rotation: 0,
        pins: [
          { id: "pos", relX: 0, relY: -30 },
          { id: "neg", relX: 0, relY: 30 },
        ],
        params: { voltage: 5 },
        state: {},
      },
      {
        id: "xor1",
        type: "logic_xor",
        label: "XOR (Sum)",
        x: 300,
        y: 120,
        rotation: 0,
        pins: [
          { id: "in1", relX: -30, relY: -15 },
          { id: "in2", relX: -30, relY: 15 },
          { id: "out", relX: 30, relY: 0 },
        ],
        params: {},
        state: {},
      },
      {
        id: "and1",
        type: "logic_and",
        label: "AND (Carry)",
        x: 300,
        y: 280,
        rotation: 0,
        pins: [
          { id: "in1", relX: -30, relY: -15 },
          { id: "in2", relX: -30, relY: 15 },
          { id: "out", relX: 30, relY: 0 },
        ],
        params: {},
        state: {},
      },
      {
        id: "led_sum",
        type: "led",
        label: "Sum LED",
        x: 480,
        y: 120,
        rotation: 90,
        pins: [
          { id: "anode", relX: -25, relY: 0 },
          { id: "cathode", relX: 25, relY: 0 },
        ],
        params: { ledColor: "#22c55e" },
        state: {},
      },
      {
        id: "led_carry",
        type: "led",
        label: "Carry LED",
        x: 480,
        y: 280,
        rotation: 90,
        pins: [
          { id: "anode", relX: -25, relY: 0 },
          { id: "cathode", relX: 25, relY: 0 },
        ],
        params: { ledColor: "#3b82f6" },
        state: {},
      },
      {
        id: "gnd1",
        type: "ground",
        label: "GND",
        x: 200,
        y: 380,
        rotation: 0,
        pins: [{ id: "p1", relX: 0, relY: -20 }],
        params: {},
        state: {},
      },
    ],
    wires: [
      { id: "w1", fromComponentId: "dc5v", fromPinId: "pos", toComponentId: "sw_a", toPinId: "p1" },
      { id: "w2", fromComponentId: "dc5v", fromPinId: "pos", toComponentId: "sw_b", toPinId: "p1" },
      { id: "w3", fromComponentId: "sw_a", fromPinId: "p2", toComponentId: "xor1", toPinId: "in1" },
      { id: "w4", fromComponentId: "sw_b", fromPinId: "p2", toComponentId: "xor1", toPinId: "in2" },
      { id: "w5", fromComponentId: "sw_a", fromPinId: "p2", toComponentId: "and1", toPinId: "in1" },
      { id: "w6", fromComponentId: "sw_b", fromPinId: "p2", toComponentId: "and1", toPinId: "in2" },
      { id: "w7", fromComponentId: "xor1", fromPinId: "out", toComponentId: "led_sum", toPinId: "anode" },
      { id: "w8", fromComponentId: "and1", fromPinId: "out", toComponentId: "led_carry", toPinId: "anode" },
      { id: "w9", fromComponentId: "dc5v", fromPinId: "neg", toComponentId: "gnd1", toPinId: "p1" },
      { id: "w10", fromComponentId: "led_sum", fromPinId: "cathode", toComponentId: "gnd1", toPinId: "p1" },
      { id: "w11", fromComponentId: "led_carry", fromPinId: "cathode", toComponentId: "gnd1", toPinId: "p1" },
    ],
  },
  {
    id: "transformer_bridge_rectifier",
    title: "6. AC Transformer, Bridge Rectifier & Filter",
    category: "AC & Signal Processing",
    description: "220V 50Hz AC input stepped down by Transformer (10:1), full-wave rectified by Bridge Rectifier DB107, and smoothed by Capacitor Filter across 100Ω Load.",
    components: [
      {
        id: "ac1",
        type: "ac_voltage",
        label: "V1 (AC 220V 50Hz)",
        x: 80,
        y: 200,
        rotation: 0,
        pins: [
          { id: "pos", relX: 0, relY: -30 },
          { id: "neg", relX: 0, relY: 30 },
        ],
        params: { voltage: 220, frequency: 50, waveform: "sine" },
        state: {},
      },
      {
        id: "xfmr1",
        type: "transformer_step_down",
        label: "XFMR1 (10:1 Step-Down)",
        x: 230,
        y: 200,
        rotation: 0,
        pins: [
          { id: "pri1", relX: -30, relY: -20 },
          { id: "pri2", relX: -30, relY: 20 },
          { id: "sec1", relX: 30, relY: -20 },
          { id: "sec2", relX: 30, relY: 20 },
        ],
        params: { turnsRatio: 0.1 },
        state: {},
      },
      {
        id: "br1",
        type: "bridge_rectifier_db107",
        label: "BR1 (Full Bridge DB107)",
        x: 400,
        y: 200,
        rotation: 0,
        pins: [
          { id: "ac1", relX: -30, relY: -20 },
          { id: "ac2", relX: -30, relY: 20 },
          { id: "dc_plus", relX: 30, relY: -20 },
          { id: "dc_minus", relX: 30, relY: 20 },
        ],
        params: {},
        state: {},
      },
      {
        id: "r1",
        type: "resistor",
        label: "R1 (100Ω Load)",
        x: 540,
        y: 180,
        rotation: 0,
        pins: [
          { id: "p1", relX: 0, relY: -40 },
          { id: "p2", relX: 0, relY: 40 },
        ],
        params: { resistance: 100 },
        state: {},
      },
      {
        id: "c2",
        type: "cap_electrolytic_10u",
        label: "C2 (10µF Filter)",
        x: 630,
        y: 180,
        rotation: 0,
        pins: [
          { id: "p1", relX: 0, relY: -30 },
          { id: "p2", relX: 0, relY: 30 },
        ],
        params: { capacitance: 0.00001 },
        state: {},
      },
      {
        id: "vm1",
        type: "voltmeter",
        label: "VM1 (DC Output Meter)",
        x: 720,
        y: 180,
        rotation: 0,
        pins: [
          { id: "p1", relX: 0, relY: -30 },
          { id: "p2", relX: 0, relY: 30 },
        ],
        params: {},
        state: {},
      },
      {
        id: "gnd1",
        type: "ground",
        label: "GND",
        x: 540,
        y: 320,
        rotation: 0,
        pins: [{ id: "p1", relX: 0, relY: -20 }],
        params: {},
        state: {},
      },
    ],
    wires: [
      { id: "w1", fromComponentId: "ac1", fromPinId: "pos", toComponentId: "xfmr1", toPinId: "pri1" },
      { id: "w2", fromComponentId: "ac1", fromPinId: "neg", toComponentId: "xfmr1", toPinId: "pri2" },
      { id: "w3", fromComponentId: "xfmr1", fromPinId: "sec1", toComponentId: "br1", toPinId: "ac1" },
      { id: "w4", fromComponentId: "xfmr1", fromPinId: "sec2", toComponentId: "br1", toPinId: "ac2" },
      { id: "w5", fromComponentId: "br1", fromPinId: "dc_plus", toComponentId: "r1", toPinId: "p1" },
      { id: "w6", fromComponentId: "br1", fromPinId: "dc_plus", toComponentId: "c2", toPinId: "p1" },
      { id: "w7", fromComponentId: "br1", fromPinId: "dc_plus", toComponentId: "vm1", toPinId: "p1" },
      { id: "w8", fromComponentId: "br1", fromPinId: "dc_minus", toComponentId: "r1", toPinId: "p2" },
      { id: "w9", fromComponentId: "br1", fromPinId: "dc_minus", toComponentId: "c2", toPinId: "p2" },
      { id: "w10", fromComponentId: "br1", fromPinId: "dc_minus", toComponentId: "vm1", toPinId: "p2" },
      { id: "w11", fromComponentId: "r1", fromPinId: "p2", toComponentId: "gnd1", toPinId: "p1" },
    ],
  },
];
